
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftPLUSMINUSleftMULTDIVrightPOWDIV LPAREN MINUS MULT NEWLINE NUMBER PLUS POW RPARENinput : input : input lineline : NEWLINEline : expr NEWLINEexpr : NUMBERexpr : MINUS NUMBERexpr : LPAREN expr RPARENexpr : expr PLUS exprexpr : expr MINUS exprexpr : expr MULT exprexpr : expr DIV exprexpr : expr POW expr'
    
_lr_action_items = {'NEWLINE':([0,1,2,3,4,5,8,14,16,17,18,19,20,21,],[-1,3,-2,-3,8,-5,-4,-6,-8,-9,-10,-11,-12,-7,]),'NUMBER':([0,1,2,3,6,7,8,9,10,11,12,13,],[-1,5,-2,-3,14,5,-4,5,5,5,5,5,]),'MINUS':([0,1,2,3,4,5,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,],[-1,6,-2,-3,10,-5,6,-4,6,6,6,6,6,-6,10,-8,-9,-10,-11,-12,-7,]),'LPAREN':([0,1,2,3,7,8,9,10,11,12,13,],[-1,7,-2,-3,7,-4,7,7,7,7,7,]),'$end':([0,1,2,3,8,],[-1,0,-2,-3,-4,]),'PLUS':([4,5,14,15,16,17,18,19,20,21,],[9,-5,-6,9,-8,-9,-10,-11,-12,-7,]),'MULT':([4,5,14,15,16,17,18,19,20,21,],[11,-5,-6,11,11,11,-10,-11,-12,-7,]),'DIV':([4,5,14,15,16,17,18,19,20,21,],[12,-5,-6,12,12,12,-10,-11,-12,-7,]),'POW':([4,5,14,15,16,17,18,19,20,21,],[13,-5,-6,13,13,13,13,13,13,-7,]),'RPAREN':([5,14,15,16,17,18,19,20,21,],[-5,-6,21,-8,-9,-10,-11,-12,-7,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'input':([0,],[1,]),'line':([1,],[2,]),'expr':([1,7,9,10,11,12,13,],[4,15,16,17,18,19,20,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> input","S'",1,None,None,None),
  ('input -> <empty>','input',0,'p_input_empty','main.py',236),
  ('input -> input line','input',2,'p_input_lines','main.py',241),
  ('line -> NEWLINE','line',1,'p_line_newline','main.py',246),
  ('line -> expr NEWLINE','line',2,'p_line_expr','main.py',251),
  ('expr -> NUMBER','expr',1,'p_expr_number','main.py',268),
  ('expr -> MINUS NUMBER','expr',2,'p_expr_minus_number','main.py',273),
  ('expr -> LPAREN expr RPAREN','expr',3,'p_expr_paren','main.py',279),
  ('expr -> expr PLUS expr','expr',3,'p_expr_binop_plus','main.py',284),
  ('expr -> expr MINUS expr','expr',3,'p_expr_binop_minus','main.py',289),
  ('expr -> expr MULT expr','expr',3,'p_expr_binop_mult','main.py',294),
  ('expr -> expr DIV expr','expr',3,'p_expr_binop_div','main.py',299),
  ('expr -> expr POW expr','expr',3,'p_expr_binop_pow','main.py',304),
]
